### PR TITLE
Refactor server method to have overall logic up top and implementatio…

### PR DESCRIPTION
**Pull request by voxlol**
One thing I learned at BAH is too keep the purposeful logic of the file up top and keep implementation details lower down. I think this will help manage your code as the projects bigger. Let me know what ya'll think.

### CODE REVIEW

**Comment by yangez** [comment]
So like a header file. Makes sense

**Comment by voxlol** [comment]
I wrapped it in an IIFE so you don't pollute the global namespace....so you can go crazy with variables names inside of it

**Comment by yangez** [comment]
Nice! I've never done that before; the Meteor.methods will still get exposed and everything?

**Comment by voxlol** [comment]
Yea, it'll just run inside the IIFE instead. And Meteor obj should be accessible through closure. It's just a nice way to keep your code self-contained, and not messing up each other as the project size grows.

**Comment by theevenprime2** [comment]
Tested.  LGTM :+1:

**Pull request merged**
